---
networks:
  backend:
    external: false

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: "watchtower"
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest${RUSTDESK_ARM64_SUFFIX}
    command: hbbs -r ${RUSTDESK_DOMAIN}:21117
    volumes:
      - ./data:/root
    networks:
      - backend
    depends_on:
      - hbbr
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest${RUSTDESK_ARM64_SUFFIX}
    command: hbbr -k _
    volumes:
      - ./data:/root
    networks:
      - backend
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
